export const NAMES = [
  "Arya Stark",
  "Jon Snow",
  "Tyrion Lannister",
  "Daenerys Targaryen",
  "Bran Stark",
  "Sansa Stark",
  "Cersei Lannister",
  "Jaime Lannister",
  "Robb Stark",
  "Jorah Mormont",
  "Samwell Tarly",
  "Theon Greyjoy",
  "Margaery Tyrell",
  "Stannis Baratheon",
  "Davos Seaworth",
  "Melisandre",
  "Gendry",
  "Bronn",
  "Varys",
  "Petyr Baelish",
  "Shae",
  "Jaqen H’ghar",
  "Tormund Giantsbane",
  "Ygritte",
  "Roose Bolton",
  "Ramsay Bolton",
  "Oberyn Martell",
  "Ellaria Sand",
  "Grey Worm",
  "Missandei",
];
